name: PatoTrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  intl: ^0.19.0
  provider: ^6.1.2
  path: ^1.9.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  flutter_pin_code_fields: ^2.2.0
  local_auth: ^2.2.0
  flutter_local_notifications: ^17.2.1
  flutter_sms_inbox: ^1.0.3
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  
  cloud_firestore: ^5.0.1
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.12.0
  http: ^1.2.1

  # NEW: Package for creating a secure upload signature
  crypto: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mpesa_logo.png